### ISSUE TITLE
Ideas for Background

### ISSUE THREAD

**Issue by Randomname537** [Blondazz/KeyOverlay#1]
I think it would be much nicer if we had the option to use a custom background, or the ability to make the background transparent. 
![Screenshot 2021-08-30 162729](https://user-images.githubusercontent.com/34945940/131408238-7daa3486-1996-4773-9b6f-987b9dab1f27.png)
something like this for custom BG.

**Comment by Randomname537** [comment]
also being able to change the color of the bars/keys

**Comment by Blondazz** [comment]
Transparent background will default to the black one so it's not really a possibility, but I will ad background changing for easier color keying and custom backgrounds are a neat idea. I'll get to it as soon as i will have access to my desktop so in like 3 days.

**Comment by Blondazz** [comment]
Added support for backgrounds!
