### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lisekden420** [Blondazz/KeyOverlay#10]
The type initializer for 'KeyOverlay.CreateItems' threw an exception.

**Comment by Blondazz** [comment]
Can you post the config file content in a comment please?

**Comment by lisekden420** [comment]
keyAmount=2
key1=Z
key2=X
key3=C
key4=V
key5=B
key6=N
key7=M
displayKey1=Z
displayKey2=X
keyCounter=yes
windowHeight=700
windowWidth=240
keySize=70
barSpeed=600
margin=25
outlineThickness=5
fading=yes
backgroundColor=0,0,0,255
keyColor=0,0,0,0
borderColor=255,255,255,255
barColor=255,255,255,100
fontColor= 255,255,255,255
backgroundImage=
maxFPS=99

**Comment by Blondazz** [comment]
Does this happen on launch? everything works fine when i put your settings in, have you tried redownloading?

**Comment by lisekden420** [comment]
yeah it does, redownload doesnt help

**Comment by Blondazz** [comment]
Really hard to say what went wrong, I cannot replicate the bug. Please add me on discord Blondazz#4321 and we can try solving it.
