### ISSUE TITLE
Does not accept symbols as input characters.

### ISSUE THREAD

**Issue by Cailus** [Blondazz/KeyOverlay#11]
Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
Invalid key .
--
My osu! keys: "," and ".".

**Comment by lisekden420** [comment]
https://www.sfml-dev.org/documentation/2.5.1/classsf_1_1Keyboard.php#acb4cacd7cc5802dec45724cf3314a142 

I think this will solve your problems

**Comment by Blondazz** [comment]
>https://www.sfml-dev.org/documentation/2.5.1/classsf_1_1Keyboard.php#acb4cacd7cc5802dec45724cf3314a142

use Comma and Period
