### ISSUE TITLE
Numpad Keys

### ISSUE THREAD

**Issue by NzudemK** [Blondazz/KeyOverlay#12]
I'm playing 4k mania with left hand: F/G and right hand: 4/5 on the num pad, and the numpad input isn't recognized

**Comment by Blondazz** [comment]
Are you using these keywords? Please check for any mispells as they are case sensitive.
![opera_vhYm5DNkvb](https://user-images.githubusercontent.com/35583718/134483280-bc8da0ea-8c17-4c55-afef-b2ca6b8f425b.png)
