### ISSUE TITLE
Linux Support?

### ISSUE THREAD

**Issue by TheChurros** [Blondazz/KeyOverlay#13]
Is there any possible way to get Linux support for this? After an hour of messing with wine I managed to get the program to run, but it only works if the program is focused. Is there a possibility of a native Linux release?

**Comment by Blondazz** [comment]
Please try using this https://puu.sh/If8uX/36695a6c8d.zip build, You will need dotnet 5.0 or higher and the csfml package and then run it with the terminal. Should work, if it doesn't you might need to build it yourself maybe.
