### ISSUE TITLE
KeyOverlay glitching at the top.

### ISSUE THREAD

**Issue by NLD-Dev** [Blondazz/KeyOverlay#18]
The application gets a white bar when i press a few times. 

Is there a way i could fix this? Or is this built into the program itself.

![image](https://user-images.githubusercontent.com/85410270/139590627-998b212c-a1fa-48b7-83b6-1a8893cceae1.png)

**Comment by Blondazz** [comment]
Have you tried the newest release? It should work better.

**Comment by NLD-Dev** [comment]
I have that version.

**Comment by Blondazz** [comment]
Please try the 1.0 then as well. It's the first time I'm seeing something like this and i have no idea  what might be causing this. Does changing bg color or using a black bg image help?

**Comment by NLD-Dev** [comment]
Ill try that. Ill get back to you soon.

**Comment by NLD-Dev** [comment]
![image](https://user-images.githubusercontent.com/85410270/139594644-c9f1a96d-54bb-4c47-bd0d-8dfdcbf0fe6b.png)
This is on the latest ver. [255,0,0,255]

![image](https://user-images.githubusercontent.com/85410270/139594721-4fdce256-ee1d-47c7-83b1-72639ef245ad.png)
This is on the latest ver. [Background used]


v1.0 works. Though i'd suggest looking into this.

Thanks!

**Comment by jowenzero** [comment]
I also have the same problem here after using this program for about an hour.

![unknown](https://user-images.githubusercontent.com/53405940/140617503-f844c072-8341-4a8e-90f5-8f16e638244d.png)

I already used the latest version so I wonder what's the issue here and hopefully it could be fixed (it would suck if I have a play butchered by this glitch during streaming haha). Thank you!

**Comment by Blondazz** [comment]
I would suggest using 1.0 version. I removed the 1.0.1 download for now because of this glitch.

**Comment by jowenzero** [comment]
Okay, I didn't notice that the 1.0.1 download has been removed so I assume 1.0 was the version I'm using. Thanks for the clarification!

**Comment by farkasma** [comment]
I am using 1.0.2 that supposedly fixed this,but  on Linux this still happens.

**Comment by Blondazz** [comment]
My bad I forgot to change the linux files

**Comment by Blondazz** [comment]
Please redownload the 1.0.2 version and check if the problem persists @farkasma

**Comment by farkasma** [comment]
Seems to be good now, thanks for the quick fix!
