### ISSUE TITLE
.NET Framework

### ISSUE THREAD

**Issue by Kakaduprroandgato** [Blondazz/KeyOverlay#21]
What .NET Framework do i use? i have 4.8 and it says that to run this program i need .NET and if i want to download it, i click yes but it does nothing. What do i do?

**Comment by Kakaduprroandgato** [comment]
i am ashamed of my username

**Comment by Blondazz** [comment]
You need .net 5 runtime

**Comment by Kakaduprroandgato** [comment]
thanks
