### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by Keegsz** [Blondazz/KeyOverlay#22]
For osu! I use the , and . key to click. When I looked at the referred to list it says that I'm not putting the wrong keys into the config. It just keeps crashing when I try to open it. Thanks for your help:)

**Comment by Blondazz** [comment]
Do you have a errorMessage.txt file in the program folder? If so can you post the contents of it?

**Comment by Keegsz** [comment]
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at KeyOverlay.AppWindow..ctor() in C:\Users\Daniel\source\KeyOverlay\AppWindow.cs:line 89
   at KeyOverlay.Program.Main(String[] args) in C:\Users\Daniel\source\KeyOverlay\Program.cs:line 13

**Comment by Keegsz** [comment]
I'm not sure if that's what you mean but when it crashes nothing comes up it just force closes

**Comment by Keegsz** [comment]
Invalid key also say . or if I put a capital letter it says , invalid then

**Comment by Blondazz** [comment]
Make sure you put Period and Comma in the config with the first letter capital

**Comment by Blondazz** [comment]
![image](https://user-images.githubusercontent.com/35583718/142492756-acb37cd2-dab9-462b-a358-8ad04d06b747.png)
Like this

**Comment by Keegsz** [comment]
Ahhhh I see thank you I had , .
