### ISSUE TITLE
Numbers such as 1,2,3... doesnt work

### ISSUE THREAD

**Issue by SleyedBasti** [Blondazz/KeyOverlay#23]
I looked up the table but it still doesnt work

i want to use 1 and 2 as my keys

**Comment by Blondazz** [comment]
![image](https://user-images.githubusercontent.com/35583718/145680588-2fe72925-b6dc-4182-b056-9421c236a98b.png)
Please make sure tou are capitalising the first letter as this setting is case sensitive

**Comment by Leclowndu93150** [comment]
> Are you using names from the left column? ![image](https://user-images.githubusercontent.com/35583718/145680588-2fe72925-b6dc-4182-b056-9421c236a98b.png) Please make sure you are capitalising the first letter as this setting is case sensitive

yeah  not working

**Comment by Blondazz** [comment]
Can you provide a screenshot of your config file?

**Comment by Leclowndu93150** [comment]
> Can you provide a screenshot of your config file?

yeah

**Comment by Leclowndu93150** [comment]
![image](https://user-images.githubusercontent.com/73310949/147392814-d5b09373-c079-4e44-b782-1a2ec83ea3a3.png)

**Comment by Blondazz** [comment]
Are you using the number row or the numpad?

**Comment by Blondazz** [comment]
![image](https://user-images.githubusercontent.com/35583718/147405717-d3f9eb07-ddc9-468f-91f1-65a7d1c80563.png)
Numpad numbers are their own separate keys

**Comment by Leclowndu93150** [comment]
oh let me try

**Comment by Leclowndu93150** [comment]
ah yes its working
