### ISSUE TITLE
Is this malware?

### ISSUE THREAD

**Issue by Kiried-Menacing** [Blondazz/KeyOverlay#26]
I scanned the files with malwarebytes and it got called a heuristics malware?
![WhyIsThisGettingFlagged](https://user-images.githubusercontent.com/86264235/149383817-09c1a9fd-dedb-4c36-b14f-ad9a1de3b29a.png)

**Comment by Blondazz** [comment]
That's gotta be a false positive, there is no malicious code. I also use malwarebytes and it never acted up like that. The code is open source so you can check for yourself, but the code is safe you should't worry just unquarantine.
