### ISSUE TITLE
i dont know how to open the program please help!!!

### ISSUE THREAD

**Issue by Herushii** [Blondazz/KeyOverlay#28]

**Comment by Blondazz** [comment]
What system are you on?

**Comment by Blondazz** [comment]
What system are you on?

**Comment by Blondazz** [comment]
I'm guessing you downloaded the source files instead of the [build](https://github.com/Blondazz/KeyOverlay/releases/tag/v1.0). If you have a problem with exe not opening then there should be an error txt file which you can paste in a comment here.

**Comment by Herushii** [comment]
what file do i download?  and also do i have to download a program to download it?

**Comment by Blondazz** [comment]
![image](https://user-images.githubusercontent.com/35583718/156140381-714eb251-14c2-4a81-8516-9545f70dd5e7.png)

**Comment by Herushii** [comment]
How do I open that file? Because it downloads with opera gx instead of the
actual file

**Comment by Blondazz** [comment]
With a progam that can open a rar archive: 7-zip, winrar etc.
