### ISSUE TITLE
Key changing

### ISSUE THREAD

**Issue by Tg11tobias** [Blondazz/KeyOverlay#32]
When I change Key1/2 the program stops working

https://youtu.be/ToPAVuVyB1U

**Comment by Blondazz** [comment]
![IMG_20220319_141032](https://user-images.githubusercontent.com/35583718/159122428-6b101df2-3b36-4609-8df7-b6815c406f13.jpg)
![Screenshot_2022-03-19-14-09-06-942_com mi globalbrowser](https://user-images.githubusercontent.com/35583718/159122433-511294d6-8777-4ba1-8886-be72db0239c6.jpg) use these namea
