### ISSUE TITLE
 this app can't run on your pc !

### ISSUE THREAD

**Issue by amir73t** [Blondazz/KeyOverlay#35]
![Capture](https://user-images.githubusercontent.com/103138837/162034802-8439ac9f-e21c-4429-8e81-2e809df7a413.PNG)
:0

**Comment by Blondazz** [comment]
Do you have .net5 runtime installed? What windows version is that?

**Comment by amir73t** [comment]
Windows 10, version 21H1 32 BIT

**Comment by jamesbt365** [comment]
build the application yourself for 32 bit if the app isn't already 32 bit

**Comment by Blondazz** [comment]
Sorry for the late response, please try this build:
[KeyOverlay.zip](https://github.com/Blondazz/KeyOverlay/files/8488764/KeyOverlay.zip)
