### ISSUE TITLE
Numpad numbers?

### ISSUE THREAD

**Issue by SkyFixing** [Blondazz/KeyOverlay#36]
I can not seem to find what the numpad numbers are called?

**Comment by SkyFixing** [comment]
I figured it out but whenever I press the keys it does not seem to work or register?

**Comment by Blondazz** [comment]
![image](https://user-images.githubusercontent.com/35583718/162061549-a2a7e6e4-cd7d-4b7e-8ece-824094352374.png)
Try these names

**Comment by SkyFixing** [comment]
That works, thank you!
