### ISSUE TITLE
if i pressed the key nothing happened to the keyoverlay

### ISSUE THREAD

**Issue by Kasshoo** [Blondazz/KeyOverlay#37]
so i setted up the keys to b and n and it work but when i try the key overlay is like freezing all the time, same with every key

**Comment by Kasshoo** [comment]
oh and now it closed by itself
or u guys called it crashed

**Comment by Blondazz** [comment]
What do you mean by freezing, did the same issue exist before changing the config?

**Comment by Alltoupload** [comment]
- [ ] Download Unity
- [ ] Recreate it with unity
