### ISSUE TITLE
it requires something to run it

### ISSUE THREAD

**Issue by Alltoupload** [Blondazz/KeyOverlay#39]
I clicked yes and downloaded it. BUT, IT TRIGGERS UAC (User Account Control)!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Blondazz** [comment]
![ok-and](https://user-images.githubusercontent.com/35583718/164077618-39015d51-0ef0-4c2f-8abf-f3605a424ce7.gif)

**Comment by Gazda99** [comment]
Yes
