### ISSUE TITLE
Cannot run on linux: libcsfml-system: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Vergenter** [Blondazz/KeyOverlay#40]
Basic system info:
```Linux pop-os 5.16.15-76051615-generic #202203161444~1647964027~21.10~e706226 SMP PREEMPT Tue Mar 22 17 x86_64 x86_64 x86_64 GNU/Linux```
Steps to reproduce:
1. Download  _KeyOverlay-ubuntu-latest.zip_ from https://github.com/Blondazz/KeyOverlay/releases/download/v1.0.1/KeyOverlay-ubuntu-latest.zip
2. unpack
3. ```cd KeyOverlay-ubuntu-latest```
4. ```chmod +x KeyOverlay``` to make it executable
5. ```./KeyOverlay``` To run it
6. Output error:
```
System.DllNotFoundException: Unable to load shared library 'csfml-system' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libcsfml-system: cannot open shared object file: No such file or directory
   at SFML.System.Clock.sfClock_create()
   at KeyOverlay.AppWindow..ctor() in /home/runner/work/KeyOverlay/KeyOverlay/AppWindow.cs:line 30
   at KeyOverlay.Program.Main(String[] args) in /home/runner/work/KeyOverlay/KeyOverlay/Program.cs:line 13
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'csfml-system' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libcsfml-system: cannot open shared object file: No such file or directory
   at SFML.System.Clock.sfClock_create()
   at KeyOverlay.AppWindow..ctor() in /home/runner/work/KeyOverlay/KeyOverlay/AppWindow.cs:line 30
   at KeyOverlay.Program.Main(String[] args) in /home/runner/work/KeyOverlay/KeyOverlay/Program.cs:line 13
Aborted (core dumped)
```
Note:
errorMessage.txt is empty

**Comment by Blondazz** [comment]
Thanks for the descriptive issue, if only all of them would look like this haha. Please check this [comment](https://github.com/Blondazz/KeyOverlay/issues/24#issuecomment-1010522461) it looks like it's the same problem with a missing package.

**Comment by Vergenter** [comment]
Installing sfml didn't solve this issue.
I installed sfml using commands below:
```
$ sudo apt-get install libsfml-dev
libsfml-dev is already the newest version (2.5.1+dfsg-1build1).
```
```
$sudo apt-get install libsfml-system2.5
libsfml-system2.5 is already the newest version (2.5.1+dfsg-1build1).
```
I'm still getting same error. 
I tried to build it myself using steps:
```
1. `dotnet restore` in main project directory
2. `dotnet add package SFML.Net --version 2.5.0` to add SFML package
3. `dotnet run` to test
Same error

**Comment by aMalteser** [comment]
Try installing `libcsfml-dev` package and running it again

**Comment by Vergenter** [comment]
Thank you for your help.
Running `sudo apt-get install libcsfml-dev` solved my problem.
I suggest to add installation instruction for ubuntu to README.MD, it will simplify this process for other people.
