### ISSUE TITLE
Is it possible to add special keys that aren't in the list?

### ISSUE THREAD

**Issue by Fozitou** [Blondazz/KeyOverlay#42]
I am from Brazil and use "D" "F" "L" "Ç" to play and as the overlay is not able to identify "Ç", i end up having to use other keys that i am not confortable playing with, so I would like to know if there is any way to add other special keys manually to this key overlay.

**Comment by Blondazz** [comment]
I remember this being an issue before and with a Brazilian keyboard as well and unfortunately there is no way to bind those keys as far as I know. If you can, try switching layouts when playing and use Semicolon, other than that I'm not sure there is anything else you could do.
