### ISSUE TITLE
Keys changing but not showing the graphics

### ISSUE THREAD

**Issue by cloudcant** [Blondazz/KeyOverlay#44]
i changed the 1st and 2nd keys to 1 and 2 in the config because that is how i play and loaded the KeyOverlay executable (im on ubuntu btw) and it changed the z and x to a 1 and 2 but wont reply to key presses of z/x and 1/2

**Comment by Blondazz** [comment]
You have to change the key1 and key2 settings to `Num1` and `Num2`, and then the displayKey1 and displayKey2 options are only for changing the text inside the squares
