### ISSUE TITLE
It doesnt work ingame

### ISSUE THREAD

**Issue by NewiiFTW** [Blondazz/KeyOverlay#46]
It works perfectly when osu! is minimized but when you focus the osu! window (in fullscreen) it suddenly stop working.

**Comment by NewiiFTW** [comment]
And if I hit the keys (G and H in my case) and suddenly alt-tab to get osu! out of focus shows as if you have touched the keys. As if the program is detecting the keys but not rendering them when osu is in first plane.

**Comment by Blondazz** [comment]
I remember some people having this issue, but I don't think I ever found the reason this happens as I don't know how to replicate it, most people with this issue either stopped responding or fixed it somehow by themselves. I'll ask around how they managed to fix that.

**Comment by Blondazz** [comment]
Does the problem also happen on v1.0.1?

**Comment by DoormatIka** [comment]
I think I found a solution.
Go to the original .exe file of osu.
Right click it > Properties > Compatibility > Check "Disable fullscreen optimizations."

It's what worked for me.

**Comment by atr6phy** [comment]
it wont let me open the .exe file for some reason, even after downloading .net 6 files required. help?

**Comment by Blondazz** [comment]
What happens when you open the .exe file exactly?

**Comment by Blondazz** [comment]
Please create a separate issue for that. This one is about a different problem
