### ISSUE TITLE
No keys showing

### ISSUE THREAD

**Issue by KingOfStableness** [Blondazz/KeyOverlay#51]
config file:
keyAmount=1
key1=mLeft
key2=J
key3=J
key4=K
key5=B
key6=N
key7=M
displayKey1=MB1
displayKey2=
keyCounter=no
windowHeight=700
windowWidth=120
keySize=70
barSpeed=600
margin=25
outlineThickness=5
fading=no
backgroundColor=255,0,0,255
keyColor=0,0,0,0
borderColor=255,255,255,255
barColor=0,125,255,255
fontColor= 255,255,255,255
backgroundImage=
maxFPS=144

**Comment by Blondazz** [comment]
The program does not support keyAmount=1, you have to set it to at least 2 and the crop it out in obs or something. When I have some time I'll try to fix this issue
