### ISSUE TITLE
Certain Keys Don't Work

### ISSUE THREAD

**Issue by JoniSpagoni** [Blondazz/KeyOverlay#54]
When changing the config file, punctuation and other punctuation-esque keys (both with shift and without) don't work. This includes comma, period, slash, backslash, semicolon, apostrophe, open and closing brackets, minus symbol, and the equals symbol.

**Comment by Blondazz** [comment]
Please send your config file

**Comment by JoniSpagoni** [comment]
[config.txt](https://github.com/Blondazz/KeyOverlay/files/10421198/config.txt)
Here you go.

**Comment by Blondazz** [comment]
Please use these names with first letter capital like in the table linked in the readme 
![image](https://user-images.githubusercontent.com/35583718/212568506-b191a20e-b249-461e-9577-944724b0b8df.png)

**Comment by JoniSpagoni** [comment]
That fixed it, thank you!
