### ISSUE TITLE
[Feature request] Read config file from command line option

### ISSUE THREAD

**Issue by UlyssesZh** [Blondazz/KeyOverlay#55]
I play multiple games, and I want a way to conveniently switch among different config files. The way I can think of is to specify the filename of config file in command line.

**Comment by Blondazz** [comment]
Do you mean the config filename when using a command line to open the program?

**Comment by UlyssesZh** [comment]
Yes. For example,

```shell
./KeyOverlay config1.txt
```

will use config1.txt instead of config.txt as the config file.

**Comment by Blondazz** [comment]
I will work on that once I get a bit of free time (like 2 weeks or so) thanks for the idea.
