### ISSUE TITLE
keys not showing while osu open.

### ISSUE THREAD

**Issue by Gamir7** [Blondazz/KeyOverlay#57]
I saw a guy posting exactly the same issue but the thread was closed, idk if he was able to fix it.
I tried what someone said in that same thread but it doesnt work for me, does someone knows a fix?

**Comment by Blondazz** [comment]
Can you link the thread that you are talking about?

**Comment by Gamir7** [comment]
> Can you link the thread that you are talking about?

sure. https://github.com/Blondazz/KeyOverlay/issues/46

**Comment by Blondazz** [comment]
Are you using window capture on the app in obs?

**Comment by DEOUosu** [comment]
I am also having the same issue and I am using window capture on the app in obs.

**Comment by DEOUosu** [comment]
I used the game capture on the app and it is working fine now.
