### ISSUE TITLE
Every time I open the program it appeared white and closed immediately

### ISSUE THREAD

**Issue by kdx046** [Blondazz/KeyOverlay#58]
Every time I open the program it appeared white and closed immediately, an 'errorMessage' popped up and stated "The type initializer for 'KeyOverlay.CreateItems' threw an exception." How can I fix this?

**Comment by Blondazz** [comment]
Please paste your config file content

**Comment by kdx046** [comment]
<img width="437" alt="config" src="https://user-images.githubusercontent.com/130243391/230779873-3e8a1337-6b10-44db-8188-29a19b110fac.png">

**Comment by Blondazz** [comment]
Please try moving the pressFontColor value to the same row as its keyword

**Comment by kdx046** [comment]
I resized the window of the text file to make it easier to capture, but it's already on the same line.
<img width="622" alt="config" src="https://user-images.githubusercontent.com/130243391/230956666-48cb2a03-8072-4a1e-8e7e-3774f62c618b.png">

**Comment by Blondazz** [comment]
I'm going to create a new release with more detailed errors which should have been there long ago I'll write here when I'm done with that

**Comment by kdx046** [comment]
Thank you very much!

**Comment by Blondazz** [comment]
Please try the newest release, the error should be more detailed there

**Comment by Blondazz** [comment]
Do you have any non latin alphabet letters in the font path?

**Comment by kdx046** [comment]
I've already installed the font given in this file but my PC still give the same error
<img width="1425" alt="font" src="https://user-images.githubusercontent.com/130243391/231465937-184cd468-17f9-4c7a-99c5-95cfe91f41b0.png">

**Comment by kdx046** [comment]
I checked my font file and I definitely have non latin alphabet

**Comment by kdx046** [comment]
I'm pretty sure that it only contains consolas

**Comment by Blondazz** [comment]
no no, in the path like here
![image](https://user-images.githubusercontent.com/35583718/231561428-80ad0d94-b4e1-4378-980a-a46ef20d0f21.png)
If there are non latin letters in the directory path then that would cause an error

**Comment by kdx046** [comment]
Fixed it, thanks a lot
