### ISSUE TITLE
Can't set shift

### ISSUE THREAD

**Issue by Jarsergej** [Blondazz/KeyOverlay#67]
Is there any way to set shift as 1 of keys? Tried write it in other ways, but always not right, help

**Comment by Blondazz** [comment]
[Here](https://www.sfml-dev.org/documentation/2.5.1/classsf_1_1Keyboard.php#acb4cacd7cc5802dec45724cf3314a142) You have all of the possible names that you can use and please keep in mind they are case sensitive. You can also find this link on KeyOverlays github page readme.
