### ISSUE TITLE
Help on MacOs

### ISSUE THREAD

**Issue by CapitalofEgypt** [Blondazz/KeyOverlay#69]
Hi, whenever i try opening the terminal, this always pops up. I don't know if i'm doing wrong or something. (Sorry Im bad at this stuff)
![Screenshot 2023-12-19 at 10 27 40 PM](https://github.com/Blondazz/KeyOverlay/assets/133549898/403abea0-d98c-4ade-aa69-1a6093c48ec8)

**Comment by Blondazz** [comment]
Sorry for the long response, please try using this command in the terminal
`xattr -dr com.apple.quarantine /path-to-KeyOverlay-folder`

**Comment by CapitalofEgypt** [comment]
Hi there, thank you for your response, I have tried using the command inside the folder and in normal terminal. I don't know if i'm still doing something wrong.
Here are the details of my Mac just in case: Mac mini M1, 2020 ver. macOS Ventura Version 13.6.1 

![Screenshot 2024-01-10 at 10 29 44 PM](https://github.com/Blondazz/KeyOverlay/assets/133549898/421a150b-2602-4019-9b3c-fe4c5df70862)

**Comment by Blondazz** [comment]
change `/path-to-KeyOverlay-folder` to the path of the directory on your mac

**Comment by CapitalofEgypt** [comment]
I'm sorry I don't understand what you mean. I got the terminal to open and downloaded the .NET program but this still pops up when ever I open the Keyoverlay Terminal
![Screenshot 2024-01-15 at 1 51 10 PM](https://github.com/Blondazz/KeyOverlay/assets/133549898/90a8a378-8464-4874-b02c-18859e9aff17)
![Screenshot 2024-01-15 at 1 51 59 PM](https://github.com/Blondazz/KeyOverlay/assets/133549898/cc6da2bf-6fdf-4651-bb3b-b094f03b1bed)

**Comment by Blondazz** [comment]
you have to substitute the `/path-to-KeyOverlay-folder` with the path to where the folder is. Where have you saved the files for the program?

**Comment by CapitalofEgypt** [comment]
It works now, Thank you for the help.
