### ISSUE TITLE
"KeyOverlay quit unexpectedlly"

### ISSUE THREAD

**Issue by insanityplays** [Blondazz/KeyOverlay#71]
Idk what's wrong here's a screenshot of the error in the terminal:
![Screen Shot 2024-04-23 at 6 25 03 PM](https://github.com/Blondazz/KeyOverlay/assets/99617278/abc6d89c-6f99-4f80-b52c-cc3222ec00f2)

**Comment by Blondazz** [comment]
Please use the names on the left side of the table that was linked in the readme section on github.
<img width="245" alt="image" src="https://github.com/Blondazz/KeyOverlay/assets/35583718/648225c6-4612-438e-8266-798ada47b5cd">

**Comment by insanityplays** [comment]
thanks!! it worked :D
