### ISSUE TITLE
. and / keys doesn't work

### ISSUE THREAD

**Issue by Evyf** [Blondazz/KeyOverlay#8]
It just close the app with error message

**Comment by Blondazz** [comment]
>key1, key2 ... - Keys the program should use (UPPERCASE), for numbers and symbols [please refer to this table](https://www.sfml-dev.org/documentation/2.5.1/classsf_1_1Keyboard.php#acb4cacd7cc5802dec45724cf3314a142)

PLEASE read the description it's there for a reason

**Comment by Evyf** [comment]
Dude If i wrote an issue it's for a reason

I read "for numbers and symbols please refer to this table"

It say that for / use /
For . use .

It doesn't work

**Comment by Evyf** [comment]
The app keep saying "Invalid Key /"
"Invalid Key ."

**Comment by Blondazz** [comment]
https://puu.sh/IaQlU/1a2a474808.png here you go, if you want . you need to use Period, for / use Slash
